language: java
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
os: linux
script: ./gradlew clean build test javadoc jacocoTestReport
jdk:
  - oraclejdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
